// FILE: ussd-middleware/routes/registerPrivy.js
// PURPOSE: Registers a Privy-authenticated user (Gmail/email) in the KULA
//          database. Called by the frontend Web3Provider after the embedded
//          wallet is provisioned and the Smart Account address is derived.
//
// ENDPOINT: POST /api/register-privy
// BODY: {
//   ownerEOA:            string  — embedded wallet address (0x...)
//   smartAccountAddress: string  — ERC-4337 counterfactual address
//   privyUserId:         string  — Privy DID (did:privy:...)
//   email?:              string  — magic-link email if used
//   googleEmail?:        string  — Google account email if used
//   tgId?:               string  — Telegram ID if previously linked
//   tgUsername?:         string
// }
//
// RESPONSE: { success: true, user: { ... } }
//
// POST /api/verify-tg-auth
// Verifies the HMAC-signed deep-link token generated by telegramBot.js
// and returns the Smart Account address.
//
// POST /api/verify-tg-initdata
// Verifies native Telegram WebApp initData (for TMA context).

'use strict';

const express  = require('express');
const { Pool } = require('pg');
const crypto   = require('crypto');
const { ethers } = require('ethers');

const router = express.Router();
const db     = new Pool({ connectionString: process.env.DATABASE_URL });

const provider = new ethers.JsonRpcProvider(process.env.BASE_SEPOLIA_RPC);
const FACTORY_ABI = [
    'function getAddress(address owner, uint256 salt) external view returns (address)',
];
const factoryContract = new ethers.Contract(
    process.env.SIMPLE_ACCOUNT_FACTORY,
    FACTORY_ABI,
    provider,
);

// ---------------------------------------------------------------------------
// HELPERS
// ---------------------------------------------------------------------------

/**
 * Derives the counterfactual Smart Account address for a Privy embedded wallet.
 * Uses salt = 0 (standard SimpleAccount for web users).
 *
 * @param {string} ownerEOA  0x-prefixed address
 * @returns {Promise<string>} Smart Account address
 */
async function derivePrivySmartAccount(ownerEOA) {
    return factoryContract.getAddress(ownerEOA, BigInt(0));
}

// ---------------------------------------------------------------------------
// ROUTE: POST /api/register-privy
// ---------------------------------------------------------------------------

router.post('/register-privy', async (req, res) => {
    const {
        ownerEOA,
        smartAccountAddress,
        privyUserId,
        email,
        googleEmail,
        tgId,
        tgUsername,
    } = req.body;

    if (!ownerEOA || !smartAccountAddress || !privyUserId) {
        return res.status(400).json({
            success: false,
            error: 'ownerEOA, smartAccountAddress, and privyUserId are required',
        });
    }

    // Normalise addresses
    const normalOwner  = ownerEOA.toLowerCase();
    const normalSA     = smartAccountAddress.toLowerCase();

    try {
        const { rows } = await db.query(
            `INSERT INTO users (
                smart_account_address,
                owner_eoa,
                privy_user_id,
                email,
                google_email,
                tg_id,
                tg_username,
                onboarding_channel,
                account_status,
                reputation_score,
                derivation_salt
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, 'PRIVY', 'PENDING', 50, '0')
            ON CONFLICT (owner_eoa) DO UPDATE
                SET privy_user_id = EXCLUDED.privy_user_id,
                    email         = COALESCE(EXCLUDED.email, users.email),
                    google_email  = COALESCE(EXCLUDED.google_email, users.google_email),
                    tg_id         = COALESCE(EXCLUDED.tg_id, users.tg_id),
                    tg_username   = COALESCE(EXCLUDED.tg_username, users.tg_username),
                    updated_at    = NOW()
            RETURNING *`,
            [
                normalSA,
                normalOwner,
                privyUserId,
                email         || null,
                googleEmail   || null,
                tgId          || null,
                tgUsername    || null,
            ],
        );

        return res.json({ success: true, user: rows[0] });
    } catch (err) {
        console.error('register-privy error:', err);
        return res.status(500).json({ success: false, error: 'Database error' });
    }
});

// ---------------------------------------------------------------------------
// ROUTE: POST /api/verify-tg-auth
// Verifies the HMAC-signed deep-link token from telegramBot.js
// ---------------------------------------------------------------------------

const DEEPLINK_EXPIRY_SECONDS = 600; // 10 minutes

router.post('/verify-tg-auth', async (req, res) => {
    const { tgAuth } = req.body;

    if (!tgAuth || typeof tgAuth !== 'string') {
        return res.status(400).json({ success: false, error: 'tgAuth token required' });
    }

    try {
        const dotIdx = tgAuth.lastIndexOf('.');
        if (dotIdx === -1) throw new Error('Malformed token');

        const payloadB64 = tgAuth.slice(0, dotIdx);
        const signature  = tgAuth.slice(dotIdx + 1);

        // Re-derive expected HMAC
        const expectedSig = crypto
            .createHmac('sha256', process.env.TG_DEEPLINK_SECRET)
            .update(payloadB64)
            .digest('hex');

        // Constant-time comparison
        if (!crypto.timingSafeEqual(
            Buffer.from(signature,    'utf8'),
            Buffer.from(expectedSig, 'utf8')
        )) {
            return res.status(401).json({ success: false, error: 'Invalid token signature' });
        }

        const payload = JSON.parse(Buffer.from(payloadB64, 'base64url').toString('utf8'));

        // Check expiry
        const age = Math.floor(Date.now() / 1000) - payload.ts;
        if (age > DEEPLINK_EXPIRY_SECONDS) {
            return res.status(401).json({ success: false, error: 'Token expired. Please request a new deep-link.' });
        }

        const { tg_id, tg_username } = payload;

        // Lookup or create user
        const { rows } = await db.query(
            'SELECT * FROM users WHERE tg_id = $1',
            [String(tg_id)]
        );

        if (rows.length === 0) {
            return res.status(404).json({
                success: false,
                error: 'Telegram user not found. Please run /kula_join in the bot first.',
            });
        }

        const user = rows[0];
        return res.json({
            success:             true,
            tgId:                user.tg_id,
            tgUsername:          user.tg_username || tg_username,
            displayName:         user.display_name,
            smartAccountAddress: user.smart_account_address,
            ownerEOA:            user.owner_eoa,
            accountStatus:       user.account_status,
            reputationScore:     user.reputation_score,
        });
    } catch (err) {
        console.error('verify-tg-auth error:', err);
        return res.status(400).json({ success: false, error: `Verification failed: ${err.message}` });
    }
});

// ---------------------------------------------------------------------------
// ROUTE: POST /api/verify-tg-initdata
// Validates native Telegram WebApp initData hash
// See: https://core.telegram.org/bots/webapps#validating-data-received-via-the-mini-app
// ---------------------------------------------------------------------------

router.post('/verify-tg-initdata', async (req, res) => {
    const { initData } = req.body;

    if (!initData || typeof initData !== 'string') {
        return res.status(400).json({ success: false, error: 'initData required' });
    }

    try {
        const params     = new URLSearchParams(initData);
        const hash       = params.get('hash');
        if (!hash) throw new Error('Missing hash in initData');

        // Build the data-check string: alphabetically sorted key=value pairs (excluding hash)
        params.delete('hash');
        const checkArr = [...params.entries()]
            .sort(([a], [b]) => a.localeCompare(b))
            .map(([k, v]) => `${k}=${v}`);
        const dataCheckString = checkArr.join('\n');

        // secret_key = HMAC-SHA256("WebAppData", BOT_TOKEN)
        const secretKey = crypto
            .createHmac('sha256', 'WebAppData')
            .update(process.env.TELEGRAM_BOT_TOKEN)
            .digest();

        const expectedHash = crypto
            .createHmac('sha256', secretKey)
            .update(dataCheckString)
            .digest('hex');

        if (!crypto.timingSafeEqual(
            Buffer.from(hash,         'hex'),
            Buffer.from(expectedHash, 'hex')
        )) {
            return res.status(401).json({ success: false, error: 'Invalid initData signature' });
        }

        // Check auth_date freshness (allow up to 24 hours)
        const authDate = parseInt(params.get('auth_date') ?? '0', 10);
        const age      = Math.floor(Date.now() / 1000) - authDate;
        if (age > 86_400) {
            return res.status(401).json({ success: false, error: 'initData expired' });
        }

        // Parse user object
        const userJson = params.get('user');
        if (!userJson) throw new Error('No user data in initData');
        const tgUser   = JSON.parse(userJson);

        // Lookup or create user in DB
        const { rows } = await db.query(
            'SELECT * FROM users WHERE tg_id = $1',
            [String(tgUser.id)]
        );

        if (rows.length === 0) {
            // First time opening TMA — auto-create account
            const { ethers: ethLib } = require('ethers');
            const innerHash = ethLib.keccak256(ethLib.toUtf8Bytes(String(tgUser.id)));
            const privateKey = ethLib.keccak256(
                ethLib.concat([
                    ethLib.getBytes(innerHash),
                    ethLib.toUtf8Bytes(process.env.KULA_SALT_SECRET),
                ])
            );
            const wallet   = new ethLib.Wallet(privateKey);
            const salt     = ethLib.keccak256(
                ethLib.concat([
                    ethLib.toUtf8Bytes(String(tgUser.id)),
                    ethLib.toUtf8Bytes(process.env.KULA_SALT_SECRET),
                ])
            );
            const saltUint = BigInt(salt);
            const smartAccountAddress = await factoryContract.getAddress(wallet.address, saltUint);

            const displayName = [tgUser.first_name, tgUser.last_name].filter(Boolean).join(' ');

            const insertResult = await db.query(
                `INSERT INTO users (
                    smart_account_address, tg_id, tg_username, display_name,
                    owner_eoa, derivation_salt, onboarding_channel, account_status, reputation_score
                ) VALUES ($1,$2,$3,$4,$5,$6,'TELEGRAM','PENDING',50)
                ON CONFLICT (tg_id) DO UPDATE
                    SET tg_username = EXCLUDED.tg_username, updated_at = NOW()
                RETURNING *`,
                [
                    smartAccountAddress, String(tgUser.id), tgUser.username || null,
                    displayName || null, wallet.address, salt.toString(),
                ]
            );
            const newUser = insertResult.rows[0];
            return res.json({
                success: true,
                tgId: newUser.tg_id, tgUsername: newUser.tg_username,
                displayName: newUser.display_name,
                smartAccountAddress: newUser.smart_account_address,
                ownerEOA: newUser.owner_eoa, accountStatus: newUser.account_status,
                reputationScore: newUser.reputation_score,
            });
        }

        const user = rows[0];
        return res.json({
            success: true,
            tgId: user.tg_id, tgUsername: user.tg_username,
            displayName: user.display_name,
            smartAccountAddress: user.smart_account_address,
            ownerEOA: user.owner_eoa, accountStatus: user.account_status,
            reputationScore: user.reputation_score,
        });
    } catch (err) {
        console.error('verify-tg-initdata error:', err);
        return res.status(400).json({ success: false, error: `Verification failed: ${err.message}` });
    }
});

module.exports = router;
